google_analytics: UA-53728067-1

destination: docs
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Site settings incl. SEO
# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
title: J3ZZ
email: contact@j3zz.com
url: https://www.j3zz.com
tagline: "All you need to know about J3ZZ - music composer, producer & sound artist"
description: "Ambient blend of bio sounds, electronics & strings <br /> Human x Nature x Technology"
author: J3ZZ
twitter:
  username: iamj3zz
  card: summary
facebook:
  app_id: 730091681068806
  publisher: 354588793499
  admins: 611780478
logo: /img/j3zz-logo-300pxwide.png
social:
  name: J3ZZ
  links:
    - https://twitter.com/iamj3zz
    - https://www.facebook.com/iamj3zz
    - https://www.instagram.com/iamj3zz
    - https://www.youtube.com/iamj3zz
    - https://www.twitch.tv/iamj3zz

# <meta name="google-site-verification" content="RU4Wgh8e3rOsG-tnE8UubmcrAQZa15w9OZUwgjIRNAI" />
# <meta name="msvalidate.01" content="1234" />
# <meta name="alexaVerifyID" content="1234" />
# <meta name="yandex-verification" content="1234" />
# <meta name="baidu-site-verification" content="1234" />
webmaster_verifications:
  google: RU4Wgh8e3rOsG-tnE8UubmcrAQZa15w9OZUwgjIRNAI
  # bing: 1234
  # alexa: 1234
  # yandex: 1234
  # baidu: 1234
lang: en_US


# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: www.j3zz.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://facebook.com/iamj3zz
  - title: instagram
    url: https://instagram.com/iamj3zz
  - title: youtube
    url: https://www.youtube.com/iamj3zz/
  - title: twitch
    url: https://twitch.tv/iamj3zz
  - title: "on discord:  iamj3zz#1937"
    url: https://discord.com/channels/@me


# Music networks urls (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
music-releases:
  - title: spotify
    url: https://open.spotify.com/artist/0gsGZAcqRcoDmr6RuaKwze?si=cf5cdNT0Qo-8yZqCTc-mhg
  - title: apple
    url: https://music.apple.com/us/artist/j3zz/1506525107
  - title: deezer
    url: hhttps://www.deezer.com/us/artist/7685176
  - title: google
    url: https://play.google.com/store/music/artist?id=Actvivms23ztfdml7a4sqraijg4
  - title: amazon
    url: https://www.amazon.com/s?k=J3ZZ&i=digital-music&search-type=ss&ref=ntt_srch_drd_B00FRNMNIW

# Tour networks urls (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
tour:
  - title: All events
    url: https://www.jeromelithiaote.com/events
  - title: FB events
    url: https://www.facebook.com/iamj3zz/events/
  - title: RA events
    url: https://www.residentadvisor.net/promoter.aspx?id=98079


# Build settings
markdown: kramdown
permalink: pretty
